# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swiftGirlsChatroomWithSelfPhoto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftGirlsChatroomWithSelfPhoto

pod 'Firebase/Core' 
pod 'JSQMessagesViewController'
pod 'Firebase/Database'
pod 'Firebase/Storage'

  target 'swiftGirlsChatroomWithSelfPhotoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swiftGirlsChatroomWithSelfPhotoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
